# Generated by Django 3.1.3 on 2020-12-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='نبذة',
            field=models.TextField(blank=True, default='نبذة عنك', null=True),
        ),
    ]
