# Generated by Django 3.1.3 on 2020-12-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_نبذة'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='نبذة',
            field=models.TextField(default='نبذة عنك'),
        ),
    ]
